### ISSUE TITLE
support 2-way binding

### ISSUE THREAD

**Issue by uNmAnNeR** [PaulMaly/svelte-imask#1]
hi! thanks for plugin!
Is there a way to bind to mask values (value, rawValue, unmaskedValue, typedValue) just like in react/ angular/vue plugins?

**Comment by PaulMaly** [comment]
Yes, we should definitely implement 2-way binding in near the future. For now, you can read all these values directly:

```html
<input use:imask={options} name="phone" type="tel" on:accept={accept}>

<script>
  let unmaskedValue,
       typedValue,
       value;

  function accept({ detail: imask }) {
    unmaskedValue = imask.unmaskedValue;
    typedValue = imask.typedValue;
    value = imask.value;
  }
</script>
```

Full example in [REPL](https://svelte.dev/repl/7f7ba2795e6c466295bc1a60ed4e941a?version=3.15.0).

**Comment by uNmAnNeR** [comment]
ok, thanks. but how to initialize input value (value/unmaskedValue/typedValue) from model?

**Comment by PaulMaly** [comment]
Hm, I believe you shouldn't be able to initialize anything except input tag attributes and imask initial options. Both are simple:

```html
<input use:imask={options} {value} name="phone" type="tel" on:accept={accept}>

<script>
  const options = { 
    mask: '+{7}(000)000-00-00',
    lazy: false,
    placeholderChar: '#'
  };

  let unmaskedValue,
       typedValue,
       value = '9100001010';

  function accept({ detail: imask }) {
    unmaskedValue = imask.unmaskedValue;
    typedValue = imask.typedValue;
    value = imask.value;
  }
</script>
```

[REPL](https://svelte.dev/repl/7f7ba2795e6c466295bc1a60ed4e941a?version=3.15.0)

**Comment by uNmAnNeR** [comment]
True, but in your case input value is always masked. So it is not possible to initialize value from unmasked or typed value, is it?

**Comment by PaulMaly** [comment]
I'm not sure how exactly it happens in iMask usually but it seems if you want to initialize input value with unmasked value just once, you already able to do that:

```
<input value={initialValue}>
```
[REPL](https://svelte.dev/repl/7f7ba2795e6c466295bc1a60ed4e941a?version=3.15.0)

In this case, you don't want to change `initialValue` variable on user input. So just keep it.

**Comment by uNmAnNeR** [comment]
this will not work in case when unmaskedValue != value, for instance let's take `{ mask: '100' }`. And i want to use unmasked value "1". In your case i end up with "1" value in input, but it should be "11", because first char is fixed and is not part of unmasked value.
So you did only the 'getter' from imask, but still there is no support for setting values other than masked.

**Comment by PaulMaly** [comment]
Could you please create REPL example for this case?

**Comment by Miaourt** [comment]
I don't know if it's related to this "2 ways bindings", tell me if I need to open another issue, but when I bind a value in a, say, store, my console keep spamming this :
``Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.``

I believe using a mask on an input that is binded on a store (like, ya know `$myStoreObj`) might cause issue here :c

**Comment by PaulMaly** [comment]
@Miaourt Could you please provide a REPL example as well? Fyi, you can just import `svelte-imask` inside a REPL and write exact example we should check.

**Comment by Miaourt** [comment]
@PaulMaly Here you go https://svelte.dev/repl/45bceb4296f643dfbb7b22e7fadd89ec?version=3.15.0

**Comment by PaulMaly** [comment]
@Miaourt Seems, right now we can't use Svelte's 2way-bindings because binding happens immediately and even if imask don't accept input. So, you should use events to change state value. We'll try to solve this inside MaskedInput component in the near future.

Re-written example: https://svelte.dev/repl/7947c45853cd4fb8808bb24c34c95e1e?version=3.15.0

**Comment by Miaourt** [comment]
@PaulMaly Thanks for help, this one indeed work with Number

Now, when I need to put a more complex mask, I get the error back, even with your fixed example https://svelte.dev/repl/d469a000602d421ab36ff51d60bd3ca4?version=3.15.0

If we make abstraction of the weird mask already showing up, after filling the input (wich work), tryc deleting the content, it's impossible :'D

**Comment by PaulMaly** [comment]
@Miaourt Because of the problem in 2way data flow, as a workaround you can set initial value just once:

```html
<script>
  ...
  const initialVal = $phone;
</script>

<input on:accept={accept} use:imask={ phoneMask } type="tel" value={initialVal} class="form-input"/>
```
[REPL](https://svelte.dev/repl/9b8132db36d94549830a0c967e98386a?version=3.15.0)

But we definitely should move this rain dancing to `MaskedInput` component. I'll think about it, I promise.

**Comment by uNmAnNeR** [comment]
@PaulMaly 

> Could you please create REPL example for this case?

https://svelte.dev/repl/53f6a4cfbe7d48d9b9effae46449237c?version=3.15.0
input should be '111', not '11'.

**Comment by PaulMaly** [comment]
@uNmAnNeR I'm not sure but seems it's not an issue of `svelte-imask`, but an issue of `imask` itself. Please check this [example](https://jsbin.com/fijodajeno/edit?html,js,output). It's similar to your example but only on vanilla js and `imask`.

**Comment by uNmAnNeR** [comment]
@PaulMaly `imask` is fine. Yes, examples are identical, but plugin should work in other way.
Html input value is always in masked format, so `imask` always works in `masked` mode while interracting with html input. But for convinience all imask plugins provide extra `unmask` property to choose which value to use. It can be just `value`, `unmaskedValue` and `typedValue`. So plugin is responsible for transforming values between low level `imask` layer and application model layer.
So if you'd like to find an example take a look at imask plugins, not imask core. All imask plugins are implemented this way and working quite well.

**Comment by PaulMaly** [comment]
@uNmAnNeR I'm not sure how the other plugins work, but `svelte-imask` is a simple wrapper around `imask`. It gives you full control over `imask` by providing access to full `imask` options,  events and even instance itself (inside events). The main reason we need this plugin because we need to sync `imask` manipulations with the element's life-cycle which is managed by Svelte.

Btw, I checked Vue's `IMaskDirective` and it's working the same way on the same example, but even worst, because there I got a problems with focusing on input. [Check it out.](https://codesandbox.io/s/vue-template-yo155?fontsize=14&hidenavigation=1&theme=dark)

![IMaskDirective](https://user-images.githubusercontent.com/4378873/69892236-761b5d80-1314-11ea-987f-81e4d177908f.gif)

**Comment by PaulMaly** [comment]
@Miaourt @uNmAnNeR The latest version of `MaskedInput` component supports 2way-binding for `value` prop like this:

```html
<MaskedInput bind:value {options} />

<script>
   let value;
</script>
```

I will close this for now. Feel free to re-open if it would be necessary.

**Comment by uNmAnNeR** [comment]
@PaulMaly Your fix looks very strange for me, mixed `unmasked`, tick, and `typed`...  WTF? Just can't understand what's going on. Vue directive is a bad example as you've already known. You could check angular directive or vue component to get the idea.

**Comment by PaulMaly** [comment]
@uNmAnNeR 

> Your fix looks very strange for me, mixed unmasked, tick, and typed... WTF? Just can't understand what's going on.

I'm not sure why, but `imask.updateValue()` doesn't work. The only way to actualize the value, I found, is to assign a new value to `typedValue`. 

Look like a workaround, right, but it works as expected. Btw, I found this solution [here](https://github.com/uNmAnNeR/imaskjs/issues/61#issuecomment-391050350). 

And of course, I should use`tick()` to be sure that `typedValue` will be updated after state changes been applied by Svelte.

> Vue directive is a bad example as you've already known. You could check angular directive or vue component to get the idea.

Actually, I don't seek to make `svelte-imask` similar to the other solutions. Right now it's quite enough to use imask with svelte in a simple and convenient way.

> WTF?

Keep polite, please.

**Comment by pesochek** [comment]
I still don't see it's working correctly in a 2 way binding. Here's an example where initial value gets updated with some delay (from the API call let's say):

https://svelte.dev/repl/8999aeadd8a94e03ad1d41ab53b13c5c?version=3.23.0

And click on the input field causes:

> "Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly."
