### ISSUE TITLE
compile warning?

### ISSUE THREAD

**Issue by cycle4passion** [PaulMaly/svelte-imask#3]
When importing and using imask, why am I getting the error:
**'imask' is imported from external module 'svelte-imask' but never used**

`
import { imask } from "svelte-imask";
const smsOptions = {mask: "(000) 000-0000"};
<input
        type="tel"
        id="sms"
        bind:value={sms}
        name="sms"
        placeholder="(123) 456-7890"
        use:imask={smsOptions}
/>
`

**Comment by PaulMaly** [comment]
Hi! Strange, I can reproduce this warning in [REPL](https://svelte.dev/repl/ad39ff39088446d09b53fd5fb2358d94?version=3.20.1). Are you sure your project set up correctly?

**Comment by cycle4passion** [comment]
I suspect it is something particular to Sapper, and yes Svelte v3 REPL works for me as well. So I did clean install sapper

```
npx degit "sveltejs/sapper-template#rollup" my-app
cd my-app
npm install
npm install --save svelte-imask
code .
-------------
// add

<script>
  import { imask } from "svelte-imask";
  const smsOptions = { mask: "(000) 000-0000" };
  let sms = "";
</script>

const smsOptions = {mask: "(000) 000-0000"}; <input type="tel" id="sms" bind:value={sms} name="sms" placeholder="(123) 456-7890" use:imask={smsOptions} />
```
----
`npm run dev`

Server complains:
src/routes/index.svelte changed. rebuilding...
✔ service worker (74ms)
• server
'imask' is imported from external module 'svelte-imask' but never used
✔ client (859ms)
✔ service worker (19ms)
✔ service worker (7ms)

**Comment by PaulMaly** [comment]
Seems this issue not related to `svelte-imask` directly. So, I'll close it for now. Feel free to re-open if you'll get more details about it.
